### ISSUE TITLE
Several _LOGGER calls in sensor.py are incorrect

### ISSUE THREAD

**Issue by jkfranks9** [clyra/unifics#27]
While trying to debug issue #26, I needed to change several _LOGGER calls to avoid a secondary exception.

All _LOGGER("...") calls should be _LOGGER.info("...")

The error received was as follows:

Traceback (most recent call last):
  File "/config/custom_components/unifics/sensor.py", line 196, in update_all
    if client.get('is_wired') == True:
       ^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/unifics/sensor.py", line 261, in state
    self.update_all()
  File "/config/custom_components/unifics/sensor.py", line 209, in update_all
    _LOGGER("Error while trying to update clients: %s", e)
TypeError: 'HassLogger' object is not callable

**Comment by clyra** [comment]
Hi,

My bad :-). May you send a PR?

**Comment by clyra** [comment]
Hi,

Just fixed the _logger entries.

**Comment by jkfranks9** [comment]
Thanks for the quick fix.
